name: skin_color
description: "一个Flutter肤色识别分析应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 图片选择和相机功能
  image_picker: ^1.0.4
  
  # Google ML Kit 人脸检测
  google_mlkit_face_detection: ^0.10.0
  
  # 图片处理
  image: ^4.1.3
  
  # UI图标
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true